cvp_server: cvp
spanning_tree:
    spine_priority: 4096
    leaf_priority: 8192
    mode: rapid
mlag:
    odd_side_ip: '192.168.255.254'
    even_side_ip: '192.168.255.255'
    cidr: 31
    vlan: 4094
    port_channel: 1000